spring: 
  profiles: 
    active: 
      - dev
---
spring: 
  profiles: dev #指定为开发环境
  application: 
    name: microservicecloud-config-A-dev
---
spring: 
  profiles: test #测试环境
  application: 
    name: microservicecloud-config-A-test